fix(ds):  if value is dateTime, convert it to ISOString
tailor-platform/frontend-packages pull request #200
Opened 2024-05-13 04:08 UTC by goombeer

# Background

# Changes

2024-05-13 07:15 UTC, goombeer commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.tsx
> +            const date = dayjs(value);
I used dayjs to check if value is a valid value.
In the following example, it does not behave properly,..,
```
const date1 = Date.parse('2024-02-30 23:00');
const date2 = new Date('2024-02-30 23:00');

console.log(date1); > 1709301600000
console.log(date2); > Fri Mar 01 2024 23:00:00 GMT+0900 (日本標準時)


```

2024-05-13 07:17 UTC, goombeer commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.tsx
> +          ?.type as MetaType | undefined;
I would really like to modify the following type definitions, but the scope of influence was a bit large, so this is what I did.

https://github.com/tailor-platform/frontend-packages/blob/db7109141133718bbd61b4fb1a2f7c3c910c51a6/packages/design-systems/src/components/composite/Datagrid/type.d.ts#L25

2024-05-13 07:19 UTC, goombeer commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
If columns add deps, infinite loop occurs.

2024-05-13 07:22 UTC, goombeer commented on packages/design-systems/test-setup.js
> +export const setup = async () => {
The time zone in CI was UTC, so I changed the time zone.

2024-05-14 01:50 UTC, IzumiSy commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.tsx
> +          ?.type as MetaType | undefined;
Can you update the `type` to be `MetaType` as well in this PR. I have wanted to do so, but now is the timing. IMA will be okay on that.

2024-05-14 02:07 UTC, IzumiSy requested changes

2024-05-14 02:07 UTC, IzumiSy commented on packages/design-systems/package.json
> +  "version": "0.28.1",
This PR now includes update on types (`MetaType`), so can you update here as the minor update?

```suggestion
  "version": "0.29.0",
```

2024-05-14 02:08 UTC, goombeer commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.tsx
> +          ?.type as MetaType | undefined;
Update type to  MetaType!
I was able to correct the problem successfully, and the correction area is now narrower😇
[fix(ds): update type to MetaType](https://github.com/tailor-platform/frontend-packages/pull/200/commits/5afce63387eed315922c66140c04d9f5681f557c)

2024-05-14 02:13 UTC, merged