Feature/fl 182
tailor-platform/frontend-packages pull request #227
Opened 2024-05-28 04:13 UTC by goombeer

# Background

# Changes

2024-05-28 06:31 UTC, IzumiSy commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.test.tsx
> +  it.only("generateGraphQLQueryFilter", async () => {
ここに `only` つける必要がよくわからなかったのですが、理由ありますか?

2024-05-28 06:31 UTC, IzumiSy commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +    if (prevFilter !== filter) {
フィルタの内容が同じ場合には `onChange` が呼ばれないことをテストしてほしいです

2024-05-28 06:33 UTC, goombeer commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.test.tsx
> +  it.only("generateGraphQLQueryFilter", async () => {
これはデバッグのためにつけていただけなので、後ほど消します🙇

2024-06-03 03:31 UTC, IzumiSy commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +  }, [filterRows]);
この `useEffect` はfilterRowsが変更されたタイミングで副作用として実行されているだけなので `onChange` と `setPrevFilter` は `filterChangedHandler` の中で呼び出すでも良い気がするんですが、それだと意図しない挙動になったりするんですかね?

利用者側からしたらフィルタの変更があった時だけコールバックで通知が受け取れればよいので。

2024-06-03 04:23 UTC, goombeer commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +  }, [filterRows]);
@IzumiSy 
意図しない挙動があるというよりは、

① defaultFilterが与えられた場合、初期表示でfilterを生成して利用者にフィルターを返したい
② resetFilterHandler/clearFilterHandlerを起動した場合でも、filterを生成して利用者にフィルターを返したい

という意図があり、①を実現するにしてもuseEffectを利用することは変わらないということがあり、この実装にした次第ですmm

2024-06-03 04:26 UTC, IzumiSy commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +  }, [filterRows]);
なるほど、たしかにそうですね。ありがとうございます。

2024-06-03 04:26 UTC, IzumiSy requested changes
Update the patch version in package.json please

2024-06-03 04:34 UTC, IzumiSy approved these changes

2024-06-03 04:34 UTC, merged