chore(storybook): migrate eslint config to Flat Config
tailor-platform/frontend-packages pull request #255
Opened 2024-06-13 13:24 UTC by toiroakr

# Background

In ESLint v9, Flat Config is the default. So we should migrate it for updating. ref. #252, #254

# Changes

migrate config and apply lint.

2024-06-13 13:31 UTC, toiroakr reviewed
大体はautofixです

2024-06-13 13:31 UTC, toiroakr commented on apps/storybook/src/main.tsx
> +ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
`@typescript-eslint/no-non-null-assertion`

2024-06-13 13:31 UTC, toiroakr commented on apps/storybook/scripts/generate-ark-types.ts
> +    const data = await response.json() as Record<string, unknown>;
`@typescript-eslint/no-unsafe-assignment`

2024-06-13 13:31 UTC, toiroakr commented on apps/storybook/scripts/generate-ark-types.ts
> +generateArkTypeFiles().then(() => console.log("completed!")).catch(console.error);
`@typescript-eslint/no-floating-promises`

2024-06-13 13:31 UTC, toiroakr commented on apps/storybook/scripts/generate-storybook-types.ts
> +    console.log("Unable to scan directory:", err);
`@typescript-eslint/restrict-template-expressions`

2024-06-13 13:31 UTC, toiroakr commented on apps/storybook/src/stories/composite/DatePicker.stories.tsx
> +  render: () => {
`prefer-arrow-functions/prefer-arrow-functions`

2024-06-13 13:31 UTC, toiroakr commented on apps/storybook/src/stories/composite/Dialog.stories.tsx
> +import { dialogTypes } from "../../ark-types";
`import/order`

2024-06-13 13:31 UTC, toiroakr commented on apps/storybook/src/stories/composite/Dialog.stories.tsx
> -
`import/order` の [newlines-between](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md#newlines-between-ignorealwaysalways-and-inside-groupsnever)

2024-06-13 13:31 UTC, toiroakr commented on apps/storybook/src/utils/ark-props.ts
> +      );
`@typescript-eslint/no-unsafe-assignment`

2024-06-13 13:33 UTC, toiroakr commented on apps/storybook/eslint.config.mjs
> +    ],
config系は追加で無視

2024-06-13 13:33 UTC, toiroakr commented on apps/storybook/tsconfig.eslint.json
> +  "include": ["src", "scripts"]
scriptsに対しても一応eslintかける用

2024-06-14 09:29 UTC, IzumiSy approved these changes

2024-06-14 11:54 UTC, toiroakr reviewed
どのくらいかわからないけど、alphaとかを外すのはeslint-plugin-react-hooksが正式にリリースするのを待ったほうがいいかもしれない？

2024-06-14 11:54 UTC, toiroakr commented on packages/dev-config/package.json
> +    "eslint-plugin-react-hooks": "5.1.0-rc-dfd30974ab-20240613",
eslint-plugin-react-hooksがcanaryじゃないと動かない
https://github.com/storybookjs/storybook/issues/22593#issuecomment-1553009031

2024-06-14 11:54 UTC, toiroakr commented on apps/storybook/eslint.config.mjs
> +  },
`react-hooks/rules-of-hooks` がStoryのrender内でhookを使うときにエラーになってしまう問題のワークアラウンド。
```tsx
export const Default: Story = {
  render: (props) => {
    const [isOpen, setIsOpen] = useState(false);
    ...
```
renderを
```tsx
export const Default: Story = {
  render: function Render(props) {
    const [isOpen, setIsOpen] = useState(false);
    ...
```
にしても `react-hooks/rules-of-hooks` は回避できるが、今度は `prefer-arrow-functions` で引っかかってしまう。

2024-06-17 00:12 UTC, IzumiSy commented on packages/dev-config/package.json
> +    "eslint-plugin-react-hooks": "5.1.0-rc-dfd30974ab-20240613",
なるほど、こういうものがやはりあるんですね

2024-06-17 00:14 UTC, IzumiSy commented on apps/storybook/eslint.config.mjs
> +  },
ここは、上記修正の通り `rules-of-hooks` を `off` にする対応で良いかなと思いました。

2024-06-17 00:22 UTC, IzumiSy commented on packages/dev-config/package.json
> +    "eslint-plugin-react-hooks": "5.1.0-rc-dfd30974ab-20240613",
これが解決するまではalphaとしておきましょう

2024-06-17 00:38 UTC, IzumiSy requested changes

2024-06-17 00:38 UTC, IzumiSy commented on packages/dev-config/package.json
version指定を `1.0.0-alpha.2` に変更お願いします。とりあえず引き続きalphaとしてリリースしましょう。

2024-06-17 03:51 UTC, toiroakr commented on packages/dev-config/package.json
@IzumiSy 変更しました

2024-06-17 03:58 UTC, IzumiSy approved these changes

2024-06-17 04:01 UTC, merged