fix(ds): Display the number of search conditons
tailor-platform/frontend-packages pull request #263
Opened 2024-06-17 02:56 UTC by goombeer

# Background

# Changes

2024-06-17 08:38 UTC, murayama-r commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +    const count = filterRows.reduce((acc, row, index) => {
自分用のメモ
filterRowsのlengthではだめ。
入力途中のフィルター条件に入っていないものまで含まれてしまうため、この処理が必要。

2024-06-18 05:59 UTC, IzumiSy commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +          row.currentState.value
これpredicateとして切り出して共通化してもらいたいです。

```
const isCurrentStateValid = (state) => {
  return (
    row.currentState.column &&
    row.currentState.condition &&
    row.currentState.value
  )
}
```

L238-L240でも使っていると思うので。

2024-06-19 00:59 UTC, IzumiSy requested changes
変更は良さそうです。package.jsonでマイナーバージョンを最後に上げてください。

2024-06-19 01:49 UTC, IzumiSy approved these changes

2024-06-19 01:49 UTC, merged