fix(ds): add a button to apply search conditions and change onChange timing
tailor-platform/frontend-packages pull request #264
Opened 2024-06-17 08:41 UTC by goombeer

# Background

https://tailor.atlassian.net/browse/FL-188

# Changes

2024-06-21 02:34 UTC, toiroakr approved these changes
多少コメントしましたが、元からだったりどっちでもよかったりという内容です。

2024-06-21 02:34 UTC, toiroakr commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.test.tsx
> +  it("useEffect is called once on first render", async () => {
元からな気がしますが、複数回useCustomFilterを呼ばないと `"useEffect is called once on first render"` がテストできていないような？

2024-06-21 02:34 UTC, toiroakr commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +    setFilterRows(emptyRow);
挙動に変更はないと思うんですけど、こういうのはどっちに寄せるとかは現状各人の好みなんですかね？

2024-06-21 02:34 UTC, toiroakr commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +      return acc;
これも元からだし好みかもですが
```suggestion
      // First row does not have jointCondition
      if (（index === 0 || row.currentState.jointCondition） && isCurrentStateValid(row)) {
          return acc + 1;
      }
      return acc;
```
のほうが読みやすいなという印象です

2024-06-24 02:50 UTC, toiroakr commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +      return acc;
isCurrentStateValidがindexありきならそもそも `isCurrentStateValid（state: FilterRowData, index: number）` でいいかも。

2024-06-26 06:20 UTC, IzumiSy commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +    setFilterRows(emptyRow);
変数に代入しておくことがこのPRの中で差分として必要ならやってもらいたいですが、不要なら無駄にdiffが増えるので基本的にはやめておきましょう、くらいのスタンスですね。

ただ明文化されていないので、そこはconfluenceに追記しておきます

2024-06-26 06:55 UTC, IzumiSy requested changes

2024-06-26 06:55 UTC, IzumiSy commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +        return state.currentState.jointCondition === "and" || "or";
このロジックだと常にtrueが返る(フォールバックされる `"or"` がtrue判定になってしまう)と思うんですが、問題ないんですかね? 

なんとなくいかが正しい気がするんですが。

```suggestion
        return state.currentState.jointCondition === "and" || state.currentState.jointCondition === "or";
```

2024-06-26 06:55 UTC, IzumiSy commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +      return acc;
higuchiさんのsuggestしてくれているやつを採用しましょう。

排他の分岐がifの条件だけに現れていた方がわかりやすいです。

2024-06-26 06:55 UTC, IzumiSy commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +  const [numberOfSearchConditions, setNumberOfSearchConditions] =
これをstateとして持つ意味ってなんですか?

`calcNumberOfSearchConditions` をメモ化して変数として扱えばそれだけで良いと思ったのですが。

2024-06-26 06:57 UTC, IzumiSy requested changes

2024-06-26 06:57 UTC, IzumiSy commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/CustomFilter.test.tsx
> +    it("If don't click apply button and close modal, UI shows prev filterRow", async () => {
このテストケースだと以下のシナリオがカバーされていない気がしました。

1. カスタムフィルタパネルからフィルタを設定
2. フィルタを適用し閉じる
3. 再度カスタムフィルタパネルを開く
4. フィルタを変更
5. 適用せず閉じる
6. 再度カスタムフィルタパネルを開き、フィルタの内容が(1)と同一であることをチェック。

2024-06-26 07:35 UTC, toiroakr commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +        return state.currentState.jointCondition === "and" || "or";
確かに。
型がちゃんとしてる前提で書くなら↓でも。
```ts
      const selectedJointCondition = oldState.find(({ currentState }) => currentState.jointCondition)?.currentState.jointCondition;
```

2024-06-28 01:36 UTC, goombeer commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +  const [numberOfSearchConditions, setNumberOfSearchConditions] =
リクエストされたUXとして、ボタンを押したらフィルターの数を計算して表示して欲しいとのことでした。
メモ化した実装の中で、ボタンを押されるまで計算をしないという条件を加えたらいけると思いますが、stateに持たせてしまった方が楽かなと思った次第です。

2024-06-28 01:52 UTC, goombeer commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +      return acc;
いただいた提案だと条件が少し抜けていたので、下記のように変更しました。
(index === 0 && isCurrentStateValid(row)) が抜けてました。
```
const calcNumberOfSearchConditions = useCallback(() => {
    const isCurrentStateValid = (state: FilterRowData) => {
      return (
        state.currentState.column &&
        state.currentState.condition &&
        state.currentState.value
      );
    };
    const count = filterRows.reduce((acc, row, index) => {
      // First row does not have jointCondition
      if (
        (index === 0 && isCurrentStateValid(row)) ||
        (row.currentState.jointCondition && isCurrentStateValid(row))
      ) {
        return acc + 1;
      }
      return acc;
    }, 0);
    return count;
  }, [filterRows]);
```

2024-06-28 02:06 UTC, toiroakr commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +      return acc;
以下の2つは論理的に同じ条件だと思います。
```ts
(index === 0 && isCurrentStateValid(row)) || (row.currentState.jointCondition && isCurrentStateValid(row))
```
```ts
（index === 0 || row.currentState.jointCondition） && isCurrentStateValid(row)
```

`isCurrentStateValid(row)` は `(index === 0 && isCurrentStateValid(row))` と 
 `(row.currentState.jointCondition && isCurrentStateValid(row))` のどちらでも必要になるのでくくりだした形に変形した結果です。

2024-06-28 02:06 UTC, goombeer commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +        return state.currentState.jointCondition === "and" || "or";
修正しました！

2024-06-28 02:24 UTC, goombeer commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +      return acc;
あー、くくりだすカッコの位置を見間違えてました、、、
修正しております。

2024-06-28 05:07 UTC, IzumiSy commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +  const [numberOfSearchConditions, setNumberOfSearchConditions] =
`filtersRows` に依存するとUIの更新で計算が再実行されるからそれはそうだと思うのですが、確定しているフィルタである `prevFilterRows` から計算すれば、状態である必要はない気がしました。それでも難しいですかね? つまり `calcNumberOfSearchConditions` はprevFilterRowsから計算されるべきなのではないかなと。

念のため、このようなコメントを自分がしている理由について補足: 状態を持つのは設計として楽なのですが、ある別の状態から導出可能なものを別の状態として持つことは、SSOTから外れてしまうので、キャッシュしたいなどよっぽどの理由がない限り設計的に可能な限り避けたい(そしてそのためにReactにはuseMemoなどの値をメモ化する関数が存在している)という理由です 🙏

2024-06-28 07:30 UTC, goombeer commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +  const [numberOfSearchConditions, setNumberOfSearchConditions] =
@IzumiSy 
こんな感じでしょうか？
[feat(ds): add useCalcNumberOfSearchConditions](https://github.com/tailor-platform/frontend-packages/pull/264/commits/596bc853d91b211b9a57a31a367615655460efbd)

2024-06-28 08:41 UTC, IzumiSy requested changes

2024-06-28 08:41 UTC, IzumiSy commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCalcNumberOfSearchConditions.ts
> +export const useCalcNumberOfSearchConditions = (
切り出したという点ではいい感じですが、この実装だと内部でReact hooksを使っていないので、そもそもこれをhooksにする必要性がないです。また、この関数は `confirmedFilterRows` が渡ってくることを前提に作られているので、設計的に密結合にしてしまった方が意図が伝わると思います。

`confirmedFilterRows`を中心にして設計すれば `useState` が登場するので、hooksとして設計する必要性が生まれるかと思います。

```ts
const useConfirmedFilterRows = () => {
  const [confirmedFilterRows, setConfirmedFilterRows] = useState<
    FilterRowData[]
  >([]);

  return {
    confirmedFilterRows,
    setConfirmedFilterRows,
    numberOfSearchConditions: getNumberOfSearchConditions(confirmedFilterRows),
  } 
}

const getNumberOfSearchConditions = (
  const useCalcNumberOfSearchConditions = (
) => {
  const isCurrentStateValid = (state: FilterRowData) => {
    return (
      state.currentState.column &&
      state.currentState.condition &&
      state.currentState.value
    );
  };
  const count = confirmedFilterRows.reduce((acc, row, index) => {
    // First row does not have jointCondition
    if (
      (index === 0 || row.currentState.jointCondition) &&
      isCurrentStateValid(row)
    ) {
      return acc + 1;
    }
    return acc;
  }, 0);

  return {
    numberOfSearchConditions: count,
  };
}

2024-06-28 08:41 UTC, IzumiSy commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +  >([]);
ここで、別コメントで自分が書いた `useConfirmedFilterRows` を使うと良いかと思います。

```ts
const {
  confirmedFilterRows,
  setConfirmedFilterRows,
  numberOfSearchConditions,
} = useConfirmedFilterRows()
```

2024-07-01 03:04 UTC, IzumiSy requested changes

2024-07-01 03:04 UTC, IzumiSy commented on packages/design-systems/src/components/composite/Datagrid/SearchFilter/useCustomFilter.ts
> +  const changePrevFilterRows = useCallback(() => {
外部から変更(change)するための引数を受け取らず、どちらかというとリセットする処理だと思うので以下の命名でお願いします。
```suggestion
  const resetToPrevFilterRows = useCallback(() => {
```

2024-07-01 09:06 UTC, IzumiSy requested changes
機能追加なのでpackage.jsonでメジャーバージョンをお願いします。

2024-07-03 02:21 UTC, goombeer commented
@IzumiSy 
2.0.0に変更しました。
[fix(ds): update version](https://github.com/tailor-platform/frontend-packages/pull/264/commits/e7aa22ed871f298e283de5dec5267355e92dc4bf)

2024-07-03 02:22 UTC, IzumiSy commented
> @IzumiSy 2.0.0に変更しました。 [fix(ds): update version](https://github.com/tailor-platform/frontend-packages/pull/264/commits/e7aa22ed871f298e283de5dec5267355e92dc4bf)

すいません、自分が間違ってました。breaking changesではない内部的な機能追加なのでメジャーバージョンアップですね... 🙏

2024-07-03 02:24 UTC, goombeer commented
@IzumiSy 
マイナーバージョンナップですよね？
1.3.0に変更しました。

2024-07-03 02:44 UTC, IzumiSy approved these changes

2024-07-03 02:44 UTC, merged