refactor(auth): separate @tailor-platform/auth/adapters/apollo to @tailor-platform/auth-apollo
tailor-platform/frontend-packages pull request #273
Opened 2024-06-20 12:50 UTC by toiroakr

# Background

By #178, auth package gave up ESM support, but we should not be against the mainstream trending to go to ESM.

We should split packages and minimize the impact caused by @apollo/client to be forced to be CJS. We could be revert the change to drop ESM then.

# Changes

Split auth package to auth and auth-apollo.

2024-06-21 00:30 UTC, toiroakr commented
本筋とは違うんですが、GitHub Pagesってコミットしなくてもデプロイできる気がするんですがコミットしてる理由ってあったりしますか？

2024-06-21 00:35 UTC, IzumiSy reviewed
全体的には良さそうな感じがしました。

2024-06-21 00:35 UTC, IzumiSy commented on packages/auth/tsup.config.ts
> +  format: ["cjs", "esm"],
ここはもうesmだけで良いかと思いました
```suggestion
  format: ["esm"],
```

2024-06-21 00:35 UTC, IzumiSy commented on packages/auth/package.json
> +      "require": "./dist/server/index.js"
この辺僕も理解が曖昧なところあるんですが古い実装のように `default` だけだと、まずいことがある感じですかね?

2024-06-21 02:35 UTC, toiroakr commented on packages/auth/package.json
> +      "require": "./dist/server/index.js"
esmだけにするなら要らないような気がします。

2024-06-21 02:49 UTC, toiroakr commented on packages/auth/tsup.config.ts
> +  format: ["cjs", "esm"],
https://hiroppy.me/blog/nodejs-new-module-algorithm/
node@20へのバックポートとかはまだマージされてないけど時間の問題っぽいので消しちゃっていいかもですね
https://github.com/nodejs/node/pull/53500

2024-06-24 00:25 UTC, murayama-r commented on .github/workflows/test_package_auth-apollo.yml
> +name: auth package CI
The file name and what is being done in auth and auth-apollo are reversed.

2024-06-24 00:28 UTC, murayama-r commented on .github/workflows/test_package_auth.yml
> +name: auth-apollo package CI
The file name and what is being done in auth and auth-apollo are reversed.

2024-06-24 00:33 UTC, murayama-r approved these changes
LGTM

2024-06-24 01:19 UTC, IzumiSy commented on packages/auth/tsup.config.ts
> +  format: ["cjs", "esm"],
そしたら、消しちゃいましょう

2024-06-24 01:20 UTC, toiroakr commented on packages/auth/tsup.config.ts
> +  format: ["cjs", "esm"],
もう消してます

2024-06-24 01:46 UTC, IzumiSy requested changes

2024-06-24 01:46 UTC, IzumiSy commented on packages/auth-apollo/package.json
> +  "peerDependencies": {
ちょっと考えたのですがいまのAuthパッケージのバージョンをpeerDepsに指定したほうがよさそうですね。

内部的にはauthパッケージがハンドリングするミドルウェアのパスに依存しているので、auth側で変更があった際に互換性を失う可能性はありそうだなと。

2024-06-24 01:52 UTC, toiroakr commented on packages/auth-apollo/package.json
> +  "peerDependencies": {
> いまのAuthパッケージのバージョン
同時にアップデートしてる場合は次の）ですよね？

`~` `^` あたりの指定はどうしましょ？
`auth` を更新するたびに `auth-apollo` を更新するのも違うと思うので `^` でいいかなーと思ってますが

2024-06-24 01:52 UTC, IzumiSy commented
> 本筋とは違うんですが、GitHub Pagesってコミットしなくてもデプロイできる気がするんですがコミットしてる理由ってあったりしますか？（レビューのときちょっと邪魔かなと）

GitHub actionsで `pnpm docsgen` をやってからGitHub pagesをデプロイするようなワークフローをつくればコミットしなくてよいと思うのですが、現状はそうなっていないので、コミットも含めてます。

ただ、邪魔なのはそのとおりなので、やめたいですね

2024-06-24 01:53 UTC, IzumiSy commented on packages/auth-apollo/package.json
> +  "peerDependencies": {
はい、ハットでお願いします🙏

2024-06-24 03:01 UTC, IzumiSy approved these changes

2024-06-24 03:02 UTC, merged