Feature/fl 189
tailor-platform/frontend-packages pull request #279
Opened 2024-06-24 11:53 UTC by onozeam

# Background

# Changes

2024-06-24 12:31 UTC, onozeam commented
手元ではこのブランチでpnpm devすると、立ち上がる。
が、このリポジトリを別にgit cloneして、同じようにこのブランチでpnpm devしても、立ち上がらない。。

2024-06-25 02:55 UTC, onozeam commented
- この状態でpnpm devするとstorybookが立ち上がる
- ↓のコメントアウトを外して pnpm devすると、立ち上がらない

https://github.com/tailor-platform/frontend-packages/pull/279/files#diff-88e1199589daa4f5c3ab667c45520244dadb6f8def1e6f5f85abd8c4f4b2fd4cR7

2024-06-25 07:39 UTC, onozeam commented
- [この状態](https://github.com/tailor-platform/frontend-packages/pull/279/commits/158f437449783c3d0378810a03857c434c04db65)だと、localでpnpm devすると立ち上がるが、chromatic上では落ちる
- [vite-plugin-reactのコメントアウト](https://github.com/tailor-platform/frontend-packages/pull/279/files#diff-88e1199589daa4f5c3ab667c45520244dadb6f8def1e6f5f85abd8c4f4b2fd4cR7)を外すと、chromaticでは立ち上がるが、localでpnpm devすると落ちる

2024-06-25 11:32 UTC, onozeam commented
こちらの記述がないとchromatic上でbuildできないが、あるとlocalのpnpm devで落ちるので、このような暫定対応にしています。
[Migration guide](https://storybook.js.org/docs/migration-guide)にも[full migration notes](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-7x-to-800)にも、それらしい記述が見当たらず。。

https://github.com/tailor-platform/frontend-packages/pull/279/files#diff-88e1199589daa4f5c3ab667c45520244dadb6f8def1e6f5f85abd8c4f4b2fd4cR7

2024-06-25 12:20 UTC, toiroakr requested changes

2024-06-25 12:20 UTC, toiroakr commented on apps/storybook/vite.config.ts
> +  plugins: process.env.CI ? [react()] : [],
CIかどうかじゃなくて `storybook dev` なのか `storybook build` なのかの違いじゃないですかね？
ローカルでbuildしてアクセスしたらエラーになる気がします。

storybookのサブコマンドで環境変数がセットされるならそれを使って、なかったら `_STORYBOOK_DEV` とか適当な環境変数セットするのがいいんじゃないかと思います。

2024-06-25 12:20 UTC, toiroakr commented on apps/storybook/vite.config.ts
> +  plugins: process.env.CI ? [react()] : [],
原因謎なままなのも気持ち悪いのでstorybook側にissue立てて、そのリンクを貼っておくとかしたいですね

2024-06-25 13:57 UTC, onozeam commented on apps/storybook/vite.config.ts
> +  plugins: process.env.CI ? [react()] : [],
確かにと思い、[ローカルでビルドしてアクセスしてみた](https://storybook.js.org/docs/sharing/publish-storybook#build-storybook-as-a-static-web-application)のですが、動作するようでした。

※ `plugins: [react()]` の記述がない状態でCIが失敗していたときのログが[こちら](https://github.com/tailor-platform/frontend-packages/actions/runs/9592813760/job/26452045034?pr=266)なんですが、buildは成功しているように見えるんですよね。(buildのあとの `Verifying your Storybook`という項目で落ちていて、[コードを追ってみると](https://github.com/chromaui/chromatic-cli/blob/main/node-src/tasks/verify.ts#L54)chromaticのGraphqQLサーバーにStoryBookをバリデーションするmutationがあるようで、その結果がFalseで落ちていた)

2024-06-25 14:24 UTC, toiroakr commented on apps/storybook/vite.config.ts
> +  plugins: process.env.CI ? [react()] : [],
手元だとコンポーネント表示してるところで `React is not defined` 出ちゃってますね
```
$ pnpm build-storybook
$ pnpx http-server storybook-static
```
<img width="1397" alt="image" src="https://github.com/tailor-platform/frontend-packages/assets/3090700/22e725db-b3f1-455f-90ba-472c2866ae97">

2024-06-25 14:30 UTC, onozeam commented on apps/storybook/vite.config.ts
> +  plugins: process.env.CI ? [react()] : [],
あー、ほんとですね

2024-06-26 00:18 UTC, IzumiSy commented on apps/storybook/vite.config.ts
> +  plugins: process.env.CI ? [react()] : [],
memo: build時にのみreact-viteのプラグインが必要になっているため、CIかどうかで分岐するのではなくdev/buildでプラグインの有効化を制御した方がよい

2024-06-26 01:08 UTC, toiroakr commented on apps/storybook/vite.config.ts
> +  plugins: process.env.CI ? [react()] : [],
@onozeam ローカルでビルドしてみて気づいたのでついでに
`apps/storybook/eslint.config.mjs` のignoresに `"storybook-static"` を足しておいてもらっていいですか？

2024-06-27 01:02 UTC, toiroakr commented on pnpm-lock.yaml
> +        version: 1.2.4
ここのバージョンが変わってAcceptedDataって型がなくて起こられてる気がします。

2024-06-27 01:49 UTC, onozeam commented on apps/storybook/vite.config.ts
> +  plugins: process.env.CI ? [react()] : [],
fixed: https://github.com/tailor-platform/frontend-packages/pull/279/commits/ddf568a50e48260bbb3101da5c10f699f641c864

2024-06-27 01:51 UTC, onozeam commented on pnpm-lock.yaml
> +        version: 1.2.4
@toiroakr ありがとうございます!
fixed: https://github.com/tailor-platform/frontend-packages/pull/279/commits/0f06a70a3b1d645a0e6e774494c8b266207d6631

2024-06-27 01:51 UTC, onozeam commented on apps/storybook/vite.config.ts
> +  plugins: process.env.CI ? [react()] : [],
> storybookのサブコマンドで環境変数がセットされるならそれを使って、なかったら _STORYBOOK_DEV とか適当な環境変数セットする

fixed: https://github.com/tailor-platform/frontend-packages/pull/279/commits/cc17fbaa8c1e8ba51dc61fa41a8c0cbf17759462

2024-06-27 01:55 UTC, toiroakr commented on pnpm-lock.yaml
> +        version: 1.2.4
すでにdesign-systems/1.2.0でリリースされてますし、export-to-csvを1.3.0に上げる方向で対応したほうがいいかなと思いました。

> packages/design-systems/package.json
```
-    "export-to-csv": "^1.2.4",
+    "export-to-csv": "^1.3.0",
```

このPRでやることでもないかなと思うので、こちらでPR作りますね
https://github.com/tailor-platform/frontend-packages/commit/0f06a70a3b1d645a0e6e774494c8b266207d6631 は取り消してもらって大丈夫です

2024-06-27 02:01 UTC, onozeam commented on pnpm-lock.yaml
> +        version: 1.2.4
了解です、戻しました

2024-06-27 02:20 UTC, onozeam commented on pnpm-lock.yaml
> +        version: 1.2.4
@toiroakr main取り込みました

2024-06-27 02:20 UTC, toiroakr approved these changes
LGTM

2024-06-27 02:25 UTC, IzumiSy requested changes

2024-06-27 02:25 UTC, IzumiSy commented on apps/storybook/vite.config.ts
> +  plugins: process.env._STORYBOOK_DEV ? [] : [react()],
このコードだけみると環境変数の存在理由が謎なので、以下のコメントを入れてもらいたいです。

```suggestion
  // Enabling react plugin prevents us from running storybook on dev, but required on Chromatic build,
  // So we put our own temporary environment variable (_STORYBOOK_DEV) to tell if it's dev or not to switch plugins.
  plugins: process.env._STORYBOOK_DEV ? [] : [react()],
```

2024-06-27 02:28 UTC, onozeam commented on apps/storybook/vite.config.ts
> +  plugins: process.env._STORYBOOK_DEV ? [] : [react()],
ありがとうございます!

2024-06-27 02:29 UTC, onozeam commented on apps/storybook/vite.config.ts
> +  plugins: process.env._STORYBOOK_DEV ? [] : [react()],
fixed: https://github.com/tailor-platform/frontend-packages/pull/279/commits/98d6e8b2ee26da3634b706dd42941258c6f0ad90

2024-06-27 02:31 UTC, IzumiSy approved these changes

2024-06-27 02:31 UTC, merged