Feature/fix tanstack version
tailor-platform/frontend-packages pull request #288
Opened 2024-07-01 02:46 UTC by murayama-r

# Background

Changed the method of specifying the version because there were cases where a different version of tanstack-table was imported on the user side of design-systems.

# Changes

This pull request primarily updates the versions of dependencies in the `design-systems` package and the `pnpm-lock.yaml` file. The changes include updating the version of the `design-systems` package, altering the version specifier for `@tanstack/table-core` and `@tanstack/react-table` from caret (`^`) to tilde (`~`), and updating the version of `@babel/helper-plugin-utils` in various dependencies in the `pnpm-lock.yaml` file.

Version updates:

* [`packages/design-systems/package.json`](diffhunk://#diff-b3c3ba59c3ba445b0f4075c962272f6058d02fa85b06b8732963cba1b4aa7cf9L3-R3): Updated the version of `@tailor-platform/design-systems` from `1.2.0` to `1.2.1`.

Dependency specifier changes:

* `packages/design-systems/package.json` and `pnpm-lock.yaml`: Changed the version specifier for `@tanstack/table-core` and `@tanstack/react-table` from caret (`^`) to tilde (`~`), which allows patch-level changes while preventing minor and major version updates. [[1]](diffhunk://#diff-b3c3ba59c3ba445b0f4075c962272f6058d02fa85b06b8732963cba1b4aa7cf9L57-R57) [[2]](diffhunk://#diff-b3c3ba59c3ba445b0f4075c962272f6058d02fa85b06b8732963cba1b4aa7cf9L80-R80) [[3]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL300-R300) [[4]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL328-R328)

Dependency version updates in `pnpm-lock.yaml`:

* Updated the version of `@babel/helper-plugin-utils` from `7.22.5` to `7.24.7` in various dependencies. [[1]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL9824-R9829) [[2]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL9844-R9849) [[3]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL9884-R9964) [[4]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL9974-R9984)
* Updated the version of `@babel/code-frame` from `7.23.5` to `7.24.7` in the `parse-json` dependency.

2024-07-01 02:47 UTC, IzumiSy requested changes
previewでIMAに組み込んで解決するか確認してみてください

2024-07-02 04:30 UTC, toiroakr approved these changes

2024-07-02 04:37 UTC, IzumiSy commented
The issue was resolved on the application side, so closing this.

2024-07-03 01:50 UTC, IzumiSy approved these changes

2024-07-03 01:50 UTC, merged