feat(ds): add Dialog component
tailor-platform/frontend-packages pull request #70
Opened 2024-02-15 06:23 UTC by murayama-r

# Background
[Bundle ark-ui](https://tailor.atlassian.net/browse/FL-98)

> Currently, our design-systems are not fully self-contained. Some components for example on Storybook requires us to install ark-ui to use implement components.
>
> From viewpoint of Developer Experience, it’s a bit clumsy that developers manually have to install ark-ui on their own side. It should be more like automated by bundling ark-ui with the specific version in design-systems.

# Changes
- add dialog component

2024-02-15 08:12 UTC, IzumiSy requested changes

2024-02-15 08:16 UTC, IzumiSy commented on packages/design-systems/src/components/composite/Dialog.tsx
> +  confirmFunction: () => void;
### 1. 命名

型定義からfunctionであることは自明なので `onConfirm` という命名にしてもらいたいです

### 2. Confirm時のDialog制御について

Confirmが押された時にDialogをクローズしたいケースがあるので、コールバックで以下のようにcloseする関数を受け取りたいです。

```suggestion
  confirmFunction: (control: { close: () => void }) => void;
```

`ArkDialog.Root` がrender functionをサポートしているので、そこでcloseする関数をこの `confirmFunction` に渡すように作りがいいかなと思っております

2024-02-15 08:19 UTC, IzumiSy commented on packages/design-systems/src/components/composite/Dialog.tsx
> +  description: string;
`description` は `ReactNode` を受け取る作りの方がいいかもしれないですね。実際のIMAのユースケースだとテキスト以外にもやりたいことがあり、これをカバーできるようになっているとよいです。
https://github.com/tailor-professional-service/ima/blob/main/apps/stock-client/src/components/providers/OverlayProvider.tsx#L48-L97

2024-02-19 08:42 UTC, IzumiSy commented on packages/design-systems/src/components/composite/Dialog.tsx
> +  setIsOpen: React.Dispatch<React.SetStateAction<boolean>>;
ここ必ずしも `React.Dispatch` が来るとは限らないので、以下のようにgenericな関数シグニチャにしてもらいたいです。

```suggestion
  setIsOpen: (isOpen: boolean) => void;
```

2024-02-19 08:44 UTC, murayama-r commented on packages/design-systems/src/components/composite/Dialog.tsx
> +  setIsOpen: React.Dispatch<React.SetStateAction<boolean>>;
あー確かに
了解しました！修正します！

2024-02-19 19:49 UTC, masato-io commented on packages/design-systems/src/components/composite/Dialog.tsx
> +    title,
titleが存在しないDialogもあると思うので、optionalでも良いかと思います。

2024-02-19 19:51 UTC, masato-io commented on packages/design-systems/src/components/composite/Dialog.tsx
> +    confirmText = "confirm",
might be more natural to use "Cancel" and "Comfirm"

2024-02-20 00:03 UTC, murayama-r commented on packages/design-systems/src/components/composite/Dialog.tsx
> +    title,
なるほど、修正します！

2024-02-20 01:12 UTC, IzumiSy approved these changes
自分からはLGTMです 👍

2024-02-20 01:29 UTC, masato-io commented on apps/storybook/src/stories/composite/Dialog.stories.tsx
> +          // title="title"
このコメントは残骸ですかね?

2024-02-20 01:32 UTC, masato-io approved these changes

2024-02-20 04:11 UTC, murayama-r commented on apps/storybook/src/stories/composite/Dialog.stories.tsx
> +          // title="title"
あ、すみません。なくてもエラーが起きないことを確認した後戻すのを忘れていました。
修正します！

2024-02-20 07:35 UTC, merged